networks:
  db_network:
    name: db_network
volumes:
  image_volume:
  bookstore_db_volume:

services:
  bookstore:
    build: .
    container_name: bookstore
    ports:
     - 8080:8080
    environment:
     - spring.datasource.url=jdbc:postgresql://bookstore_db:5432/Bookstore
    networks: 
     - db_network
    volumes: 
     - image_volume:/home/app/images
    depends_on:
     bookstore_db:
      condition: service_healthy

  bookstore_db:
    image: postgres
    container_name: bookstore_db
    ports: 
     - 5432:5432
    volumes:
     - bookstore_db_volume:/var/lib/postgresql/data 
     - ./init_script.sql:/docker-entrypoint-initdb.d/init_script.sql
    environment:
     - POSTGRES_PASSWORD=postgres
     - POSTGRES_USER=postgres
     - POSTGRES_DB=Bookstore
     - PGUSER=postgres
    networks:
     - db_network
    healthcheck:
     test: ["CMD-SHELL", "pg_isready", "-U", "postgres", "-d", "Bookstore"]
     interval: 10s
     timeout: 20s
